#!groovy

// Generated by IBM TransformationAdvisor
// Wed Nov 06 09:15:48 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'ibmexceptional'
    mvnCommands = '--version'
    test='false'
}